name: Build & Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

  # Permite ejecutar este workflow manualmente desde la pestaña de Actions
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Angular project
        run: npm run build -- --configuration=production

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx angular-cli-ghpages --dir=dist/ng_test --name="Pitter911" --email="pedrogarcia8323@gmail.com" --repo=https://github.com/Pitter911/ng_test.git --base-href=/ng_test/
